# Generated by Django 4.2.8 on 2023-12-16 16:19

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500, verbose_name="Название")),
                (
                    "participants_count",
                    models.IntegerField(default=1, verbose_name="Количество студентов"),
                ),
                ("work_date", models.DateField(verbose_name="Дата работы")),
                ("start_time", models.TimeField(verbose_name="Начало работы")),
                ("end_time", models.TimeField(verbose_name="Окончание работы")),
                (
                    "description",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True, verbose_name="Описание"
                    ),
                ),
                (
                    "administrative_points",
                    models.IntegerField(
                        default=0, verbose_name="Административные баллы"
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        blank=True, to=settings.AUTH_USER_MODEL, verbose_name="Студенты"
                    ),
                ),
            ],
            options={
                "verbose_name": "Работа",
                "verbose_name_plural": "Работы",
            },
        ),
    ]
