# Generated by Django 4.2.8 on 2023-12-18 18:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("work", "0002_work_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="nonactive_participants",
            field=models.ManyToManyField(
                blank=True,
                related_name="works",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Студенты, выполнявшие в работу",
            ),
        ),
    ]
