# Generated by Django 4.2.8 on 2023-12-23 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("work", "0003_work_nonactive_participants"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="work",
            name="nonactive_participants",
        ),
        migrations.AddField(
            model_name="work",
            name="activity_points",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Баллы ССО"
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="administrative_points",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Административные баллы"
            ),
        ),
        migrations.CreateModel(
            name="WorkHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="Статус"
                    ),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_work_history",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Студент",
                    ),
                ),
                (
                    "work_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_history",
                        to="work.work",
                        verbose_name="Работа",
                    ),
                ),
            ],
        ),
    ]
