# Generated by Django 4.2.8 on 2023-12-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("work", "0005_work_is_activity_work_work_is_administrative_work"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workhistory",
            options={
                "verbose_name": "История работы",
                "verbose_name_plural": "История работ",
            },
        ),
        migrations.AddField(
            model_name="workhistory",
            name="is_active",
            field=models.BooleanField(blank=True, null=True, verbose_name="Активно"),
        ),
    ]
