# Generated by Django 4.2.8 on 2023-12-23 13:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("work", "0007_workhistory_participants"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workhistory",
            name="participants",
        ),
    ]
