# Generated by Django 4.2.8 on 2023-12-16 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("dormitory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True, max_length=255, unique=True, verbose_name="Email"
                    ),
                ),
                ("first_name", models.CharField(max_length=255, verbose_name="Имя")),
                (
                    "second_name",
                    models.CharField(max_length=255, verbose_name="Фамилия"),
                ),
                (
                    "third_name",
                    models.CharField(max_length=255, verbose_name="Отчество"),
                ),
                (
                    "administrative_points",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name="Административные баллы",
                    ),
                ),
                (
                    "activity_points",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="Баллы ССО"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Время последнего обновления"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=12, null=True, verbose_name="Телефон"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Золото", "Золото"),
                            ("Серебро", "Серебро"),
                            ("Бронза", "Бронза"),
                        ],
                        default="Бронза",
                        verbose_name="Статус",
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="student_profile_images",
                        verbose_name="Фото",
                    ),
                ),
                (
                    "is_student",
                    models.BooleanField(default=True, verbose_name="Студент"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(default=False, verbose_name="Админ"),
                ),
                (
                    "dormitory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="dormitory.dormitory",
                        verbose_name="Общежитие",
                    ),
                ),
            ],
            options={
                "verbose_name": "Студент",
                "verbose_name_plural": "Студенты",
            },
        ),
    ]
