# Generated by Django 4.2.8 on 2023-12-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0002_studentdocument"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentdocument",
            name="file_content",
            field=models.FileField(upload_to="", verbose_name="Документ"),
        ),
    ]
