# Generated by Django 4.2.8 on 2023-12-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0004_alter_studentdocument_file_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentdocument",
            name="file_content",
            field=models.FileField(upload_to="documents/", verbose_name="Документ"),
        ),
    ]
